if (NOT DEFINED COVERAGE_BINARY_DIR OR COVERAGE_BINARY_DIR STREQUAL "")
    message(FATAL_ERROR "COVERAGE_BINARY_DIR must identify the active build directory")
endif ()

file(GLOB_RECURSE COVERAGE_COUNTER_FILES
        LIST_DIRECTORIES FALSE
        "${COVERAGE_BINARY_DIR}/*.gcda")

if (COVERAGE_COUNTER_FILES)
    file(REMOVE ${COVERAGE_COUNTER_FILES})
endif ()
